#based image
FROM tomcat:latest
#cd /usr/local/tomcat/webapps
WORKDIR /usr/local/tomcat/webapps
#Add is used to copy the local files from the docker-web to the image's docker-web
ADD docker-web ./docker-web